### ISSUE TITLE
Time data doesn't match format "%Y-%m-%d %H:%M:%S.%f%z"

### ISSUE THREAD

**Issue by shaform** [gantry-ml/gantry-demos#27]
Hi,

I am trying the run the example in the tutorial, but I encounter this error. Just want to report it here in case other people have the same problems.
```
Traceback (most recent call last):
  File ".../gantry-demos/grammar-error-corrector/backfill.py", line 124, in <module>
    load_to_gantry(data, GantryConfig.GANTRY_PROD_ENV)
  File ".../gantry-demos/grammar-error-corrector/backfill.py", line 25, in load_to_gantry
    timestamps=[ts.to_pydatetime() for ts in pd.to_datetime(df["timestamp"])],
  File ".../gantry-demos/grammar-error-corrector/venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 1050, in to_datetime
    values = convert_listlike(arg._values, format)
  File ".../gantry-demos/grammar-error-corrector/venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 453, in _convert_listlike_datetimes
    return _array_strptime_with_fallback(arg, name, utc, format, exact, errors)
  File ".../gantry-demos/grammar-error-corrector/venv/lib/python3.9/site-packages/pandas/core/tools/datetimes.py", line 484, in _array_strptime_with_fallback
    result, timezones = array_strptime(arg, fmt, exact=exact, errors=errors, utc=utc)
  File "pandas/_libs/tslibs/strptime.pyx", line 530, in pandas._libs.tslibs.strptime.array_strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 351, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data "2022-04-23 00:00:00+00:00" doesn't match format "%Y-%m-%d %H:%M:%S.%f%z", at position 46401. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
```

**Comment by shaffeeullah** [comment]
Hi @shaform ,

Thanks for calling it out! Looks like one of our dependencies changed behavior. This is now fixed on the main branch; if you pull again it should work.

**Comment by shaform** [comment]
Thanks! The error no longer happens!
